name: build and Deploy Next.js

# ビルドとデプロイをする

on:
  workflow_run:
    workflows: ["Auto Dummy Commit"]
    types:
      - completed
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: Node.js をセットアップ
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: 依存関係をインストール
        run: npm install

      - name: Next.js をビルド
        run: npm run build
        env:
          NEXT_PUBLIC_ROOT_PATH: ${{secrets.NEXT_PUBLIC_ROOT_PATH}}
          NEXT_PUBLIC_FIREBASE_API_KEY: ${{secrets.NEXT_PUBLIC_FIREBASE_API_KEY}}
          NEXT_PUBLIC_AUTH_DOMAIN: ${{secrets.NEXT_PUBLIC_AUTH_DOMAIN}}
          NEXT_PUBLIC_PROJECT_ID: ${{secrets.NEXT_PUBLIC_PROJECT_ID}}
          NEXT_PUBLIC_STORAGE_BUCKET: ${{secrets.NEXT_PUBLIC_STORAGE_BUCKET}}
          NEXT_PUBLIC_APP_ID: ${{secrets.NEXT_PUBLIC_APP_ID}}
          NEXT_PUBLIC_MESSAGING_SENDER_ID: ${{secrets.NEXT_PUBLIC_MESSAGING_SENDER_ID}}
          NEXT_PUBLIC_MEASUREMENT_ID: ${{secrets.NEXT_PUBLIC_MEASUREMENT_ID}}
          NEXT_PUBLIC_DISCORD_CLIENT_ID: ${{secrets.NEXT_PUBLIC_DISCORD_CLIENT_ID}}
          NEXT_PUBLIC_CLOUDFLARE_URL: ${{secrets.NEXT_PUBLIC_CLOUDFLARE_URL}}
          NEXT_PUBLIC_STORAGE_URL: ${{secrets.NEXT_PUBLIC_STORAGE_URL}}
          ENC_KEY: ${{secrets.ENC_KEY}}

      - name: gh-pages ブランチにデプロイ
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          publish_branch: gh-pages
